PUT http://localhost:5000/api/goals/68a70a85db0897112f3849c6 HTTP/1.1
content-type: application/json

{
    "text":"oh no how about this?"
}

###

POST http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane@doe.com",
    "password": "janedoecom"
}

### 
POST http://localhost:5000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "jane@doe.com",
    "password": "janedoecom"
}

###

GET http://localhost:5000/api/users/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YTc0NTdkNTYxYWRjZjg2ZDIyN2E5NiIsImlhdCI6MTc1NTc5Mjc2OCwiZXhwIjoxNzU4Mzg0NzY4fQ.t74xagfyUcVf7lstsyixl_K6Q5SY4FJd8aOsbRK6kgI

###

POST http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "James koo",
    "email": "james@koo.com",
    "password": "jameskoocom"
} 

###
POST http://localhost:5000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "james@koo.com",
    "password": "jameskoocom"
}


### 
POST http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Kim test",
    "email": "Kim@test.com",
    "password": "Kimtestcom"
} 

### 

POST http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Kim test",
    "password": "Kimtestcom"
} 

### 
POST http://localhost:5000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "Kim@test.com",
    "password": "Kimtestcom1"
}

### 
GET http://localhost:5000/api/users/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YTc0YzJiYWNjYmQxMDMxNGY0NjYyMSIsImlhdCI6MTc1NTc5NDQ3NSwiZXhwIjoxNzU4Mzg2NDc1fQ.NudrgxUWpVb6zjJ_Rqji7SHK_Uu8sB7XCezOWOGrQxo

### 
POST http://localhost:5000/api/goals HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YTc0YzJiYWNjYmQxMDMxNGY0NjYyMSIsImlhdCI6MTc1NTc5NDQ3NSwiZXhwIjoxNzU4Mzg2NDc1fQ.NudrgxUWpVb6zjJ_Rqji7SHK_Uu8sB7XCezOWOGrQxo

{
    "text": "kim's second goal -HAHA"
}

### 
GET http://localhost:5000/api/goals HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YTc0YzJiYWNjYmQxMDMxNGY0NjYyMSIsImlhdCI6MTc1NTc5NDQ3NSwiZXhwIjoxNzU4Mzg2NDc1fQ.NudrgxUWpVb6zjJ_Rqji7SHK_Uu8sB7XCezOWOGrQxo

###

PUT  http://localhost:5000/api/goals/68a75c926a7a43512b221ce4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YTc0YzJiYWNjYmQxMDMxNGY0NjYyMSIsImlhdCI6MTc1NTc5NDQ3NSwiZXhwIjoxNzU4Mzg2NDc1fQ.NudrgxUWpVb6zjJ_Rqji7SHK_Uu8sB7XCezOWOGrQxo

{
    "text": "Goal updated good bye"
}


###
DELETE  http://localhost:5000/api/goals/68a75ca0ccbc716a47b193ba HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YTc0YzJiYWNjYmQxMDMxNGY0NjYyMSIsImlhdCI6MTc1NTc5NDQ3NSwiZXhwIjoxNzU4Mzg2NDc1fQ.NudrgxUWpVb6zjJ_Rqji7SHK_Uu8sB7XCezOWOGrQxo

###

POST http://localhost:5000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "user1@use.com",
    "password": "user1user1"
}

### 

POST http://localhost:5000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "user2@user.com",
    "password": "user2user2"
}


###

POST http://localhost:5000/api/goals HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YTlhMzUzODVjYTk0YjYwZWRjYzRhYSIsImlhdCI6MTc1NTk3MjYyMiwiZXhwIjoxNzU4NTY0NjIyfQ.j3kCh7PR5LXv70SD-sXcXXz22RXGLgwudI3YpQ1b0dY

{
    "text": "user4's new post"
}


### get user4
GET http://localhost:5000/api/goals HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YTlhMzUzODVjYTk0YjYwZWRjYzRhYSIsImlhdCI6MTc1NTk3MjYyMiwiZXhwIjoxNzU4NTY0NjIyfQ.j3kCh7PR5LXv70SD-sXcXXz22RXGLgwudI3YpQ1b0dY

###

